# Generated by Django 2.2.7 on 2019-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='A slug for the URL for the about page.', unique=True),
        ),
    ]
