# Generated by Django 3.0.3 on 2020-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191105_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether to show this organization in the main listing.'),
        ),
    ]
