# Generated by Django 2.2.7 on 2019-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionkey',
            name='real_name',
            field=models.TextField(help_text='Enter the real name(s) of all participants(s) taking the test, one per line.', max_length=240, verbose_name='Real name(s) of participant(s), separated by newlines'),
        ),
    ]
