# Generated by Django 2.2.7 on 2019-11-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191105_1633'),
        ('hydrogen', '0002_auto_20191105_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='organization',
            field=models.ForeignKey(default=1, help_text='The organization running this contest.', on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
            preserve_default=False,
        ),
    ]
