# Generated by Django 2.2.7 on 2019-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0003_test_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_indiv',
            field=models.BooleanField(default=False, help_text='Whether the contest is individual.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionkey',
            name='real_name',
            field=models.TextField(help_text='Real name(s) of participants(s), one per line.', max_length=240, verbose_name='Real name(s) of participant(s)'),
        ),
    ]
