# Generated by Django 2.2.7 on 2019-11-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0004_auto_20191105_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_indiv',
        ),
        migrations.AddField(
            model_name='test',
            name='team_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of students per team; use 1 for individual.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='How long is the contest in minutes? Leave blank for no time limit at all.', null=True),
        ),
    ]
