# Generated by Django 2.2.7 on 2019-11-06 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0006_auto_20191105_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionkey',
            name='end_time',
        ),
        migrations.AddField(
            model_name='submissionkey',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The creation date.'),
            preserve_default=False,
        ),
    ]
