# Generated by Django 2.2.7 on 2019-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0008_auto_20191105_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='problems_url',
            field=models.TextField(help_text='The URL to the problems file or page'),
        ),
    ]
