# Generated by Django 3.0.3 on 2020-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0009_auto_20191106_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Whether to hide the test from main listing. Not meant to be a security feature.'),
        ),
    ]
