# Generated by Django 3.0.3 on 2020-02-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0010_test_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether to hide the test from main listing. Not meant to be a security feature.'),
        ),
    ]
